### ISSUE TITLE
Exit values captured in $ex, but never used

### ISSUE THREAD

**Issue by swelljoe** [virtualmin/virtualmin-init#1]
In mass.cgi and save.cgi, there's several function calls with the results captured in $ex but that variable is never used. 

For example:

https://github.com/virtualmin/virtualmin-init/blob/master/mass.cgi#L40

That's kinda smelly. If we don't need to know what happened, we shouldn't catch it. If we do need to know, we should do something with it. I'm not clever enough to know which should happen here. It looks kinda like we're outputting in the functions being called and nothing useful is returned? Am I missing something subtle like these don't work right when not forced into scalar context or something?

**Comment by jcameron** [comment]
In that case, `$ex` isn't used because the output of the action should already tell the user if it succeeded or not. I'll remove the setting of `$ex`
